# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2  # Required

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Sphinx configuration
sphinx:
  configuration: doc/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
python:
  install:
    - requirements: doc/requirements.txt
    - path: .
